apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: togglemaster
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DATABASE_URL: {{ required "auth.databaseUrl is required" .Values.auth.databaseUrl | b64enc | quote }}
  MASTER_KEY: {{ required "auth.masterKey is required" .Values.auth.masterKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  labels:
    app.kubernetes.io/name: flag-service
    app.kubernetes.io/part-of: togglemaster
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DATABASE_URL: {{ required "flags.databaseUrl is required" .Values.flags.databaseUrl | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  labels:
    app.kubernetes.io/name: targeting-service
    app.kubernetes.io/part-of: togglemaster
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  DATABASE_URL: {{ required "targeting.databaseUrl is required" .Values.targeting.databaseUrl | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  labels:
    app.kubernetes.io/name: evaluation-service
    app.kubernetes.io/part-of: togglemaster
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  SERVICE_API_KEY: {{ required "evaluation.serviceApiKey is required" .Values.evaluation.serviceApiKey | b64enc | quote }}
